-- GENERATED by db/seeds/generate-catalog-seed.ts from src/data/*.ts. Do not edit by hand.
-- Re-runnable: every insert upserts on its natural key.
-- TODO: per-side stock comes from ERPNext; until then both sides get the product's inStock count.

BEGIN;

INSERT INTO makes (name, slug) VALUES
  ('Toyota', 'toyota'),
  ('Mazda', 'mazda'),
  ('Subaru', 'subaru'),
  ('Suzuki', 'suzuki'),
  ('Nissan', 'nissan')
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO models (make_id, name, slug)
SELECT mk.id, v.name, v.slug
FROM (VALUES
  ('toyota', 'Premio', 'premio'),
  ('toyota', 'Harrier', 'harrier'),
  ('toyota', 'Probox / Succeed', 'probox-succeed'),
  ('toyota', 'Corolla', 'corolla'),
  ('toyota', 'Corolla Axio', 'corolla-axio'),
  ('toyota', 'Corolla Fielder', 'corolla-fielder'),
  ('toyota', 'Land Cruiser Prado', 'land-cruiser-prado'),
  ('toyota', 'Vitz', 'vitz'),
  ('toyota', 'Noah / Voxy', 'noah-voxy'),
  ('toyota', 'Hiace', 'hiace'),
  ('toyota', 'Allion', 'allion'),
  ('mazda', 'Demio', 'demio'),
  ('mazda', 'CX-5', 'cx-5'),
  ('subaru', 'Forester', 'forester'),
  ('suzuki', 'Alto', 'alto'),
  ('nissan', 'Tiida', 'tiida'),
  ('nissan', 'NV200 Vanette', 'nv200-vanette')
) AS v (make_slug, name, slug)
JOIN makes mk ON mk.slug = v.make_slug
ON CONFLICT (make_id, slug) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO vehicle_generations (model_id, name, slug, year_from, year_to, popular)
SELECT mo.id, v.name, v.slug, v.year_from::smallint, v.year_to::smallint, v.popular::boolean
FROM (VALUES
  ('toyota', 'premio', 'Premio 260', 'toyota-premio-260', 2007, 2016, true),
  ('toyota', 'premio', 'Premio 240', 'toyota-premio-240', 2001, 2007, true),
  ('toyota', 'harrier', 'Harrier (XU60)', 'toyota-harrier-xu60', 2014, 2019, true),
  ('toyota', 'harrier', 'Harrier (XU30)', 'toyota-harrier-xu30', 2003, 2013, false),
  ('toyota', 'probox-succeed', 'Probox / Succeed (Old)', 'toyota-probox-old', 2002, 2014, true),
  ('toyota', 'probox-succeed', 'Probox / Succeed (New)', 'toyota-probox-new', 2014, 2024, true),
  ('toyota', 'corolla', 'Corolla NZE 120/121', 'toyota-corolla-nze', 2001, 2006, true),
  ('toyota', 'corolla-axio', 'Corolla Axio 06–12', 'toyota-axio-e140', 2006, 2012, true),
  ('toyota', 'corolla-axio', 'Corolla Axio 13–19', 'toyota-axio-e160', 2013, 2019, true),
  ('toyota', 'corolla-fielder', 'Corolla Fielder 07–12', 'toyota-fielder-140', 2007, 2012, true),
  ('toyota', 'corolla-fielder', 'Corolla Fielder 13–19', 'toyota-fielder-160', 2013, 2019, true),
  ('toyota', 'land-cruiser-prado', 'Land Cruiser Prado J150', 'toyota-prado-150', 2009, 2022, true),
  ('toyota', 'vitz', 'Vitz Jewela', 'toyota-vitz-jewela', 2012, 2019, true),
  ('toyota', 'vitz', 'Vitz XP90', 'toyota-vitz-05', 2005, 2010, false),
  ('toyota', 'noah-voxy', 'Noah / Voxy 70', 'toyota-voxy-noah-70', 2007, 2013, false),
  ('toyota', 'hiace', 'Hiace 200 Series', 'toyota-hiace-200', 2005, 2020, true),
  ('toyota', 'allion', 'Allion 260 / 265', 'toyota-allion-260', 2007, 2016, false),
  ('toyota', 'allion', 'Allion 240', 'toyota-allion-240', 2001, 2007, false),
  ('mazda', 'demio', 'Demio DJ / DE', 'mazda-demio', 2012, 2019, true),
  ('mazda', 'cx-5', 'CX-5 KF / KE', 'mazda-cx5', 2012, 2022, true),
  ('subaru', 'forester', 'Forester SJ5', 'subaru-forester-sj', 2012, 2018, false),
  ('suzuki', 'alto', 'Alto HA36', 'suzuki-alto', 2015, 2022, true),
  ('nissan', 'tiida', 'Tiida C11', 'nissan-tiida-c11', 2004, 2012, false),
  ('nissan', 'nv200-vanette', 'NV200 Vanette', 'nissan-nv200', 2009, 2021, false)
) AS v (make_slug, model_slug, name, slug, year_from, year_to, popular)
JOIN makes mk ON mk.slug = v.make_slug
JOIN models mo ON mo.make_id = mk.id AND mo.slug = v.model_slug
ON CONFLICT (slug) DO UPDATE SET
  model_id = EXCLUDED.model_id, name = EXCLUDED.name, year_from = EXCLUDED.year_from,
  year_to = EXCLUDED.year_to, popular = EXCLUDED.popular;

INSERT INTO chassis_codes (generation_id, code)
SELECT g.id, v.code
FROM (VALUES
  ('toyota-premio-260', 'NZT260'),
  ('toyota-premio-260', 'ZRT260'),
  ('toyota-premio-260', 'ZRT265'),
  ('toyota-premio-240', 'AZT240'),
  ('toyota-premio-240', 'NZT240'),
  ('toyota-premio-240', 'ZZT240'),
  ('toyota-harrier-xu60', 'ZSU60'),
  ('toyota-harrier-xu60', 'ZSU65'),
  ('toyota-harrier-xu60', 'AVU65'),
  ('toyota-harrier-xu30', 'ACU30'),
  ('toyota-harrier-xu30', 'MCU30'),
  ('toyota-probox-old', 'NCP51'),
  ('toyota-probox-old', 'NCP58'),
  ('toyota-probox-old', 'NCP59'),
  ('toyota-probox-new', 'NSP160'),
  ('toyota-probox-new', 'NCP160'),
  ('toyota-probox-new', 'NHP160'),
  ('toyota-corolla-nze', 'NZE121'),
  ('toyota-corolla-nze', 'ZZE122'),
  ('toyota-axio-e140', 'NZE141'),
  ('toyota-axio-e140', 'ZRE142'),
  ('toyota-axio-e160', 'NRE160'),
  ('toyota-axio-e160', 'NZE161'),
  ('toyota-axio-e160', 'NKE165'),
  ('toyota-fielder-140', 'NZE141G'),
  ('toyota-fielder-140', 'ZRE142G'),
  ('toyota-fielder-160', 'NZE161G'),
  ('toyota-fielder-160', 'NKE165G'),
  ('toyota-prado-150', 'TRJ150'),
  ('toyota-prado-150', 'GDJ150'),
  ('toyota-vitz-jewela', 'KSP130'),
  ('toyota-vitz-jewela', 'NSP130'),
  ('toyota-vitz-05', 'SCP90'),
  ('toyota-vitz-05', 'NCP91'),
  ('toyota-voxy-noah-70', 'ZRR70'),
  ('toyota-voxy-noah-70', 'ZRR75'),
  ('toyota-hiace-200', 'KDH200'),
  ('toyota-hiace-200', 'TRH200'),
  ('toyota-allion-260', 'NZT260'),
  ('toyota-allion-260', 'ZRT261'),
  ('toyota-allion-240', 'NZT240'),
  ('toyota-allion-240', 'ZZT240'),
  ('mazda-demio', 'DE3FS'),
  ('mazda-demio', 'DJ5FS'),
  ('mazda-cx5', 'KE2FW'),
  ('mazda-cx5', 'KF2P'),
  ('subaru-forester-sj', 'SJ5'),
  ('subaru-forester-sj', 'SJG'),
  ('suzuki-alto', 'HA36S'),
  ('suzuki-alto', 'HA36V'),
  ('nissan-tiida-c11', 'C11'),
  ('nissan-tiida-c11', 'NC11'),
  ('nissan-nv200', 'M20'),
  ('nissan-nv200', 'VM20')
) AS v (generation_slug, code)
JOIN vehicle_generations g ON g.slug = v.generation_slug
ON CONFLICT (generation_id, code) DO NOTHING;

INSERT INTO products (slug, legacy_id, title, category, description, pair_price_kes, featured)
SELECT v.slug, v.legacy_id, v.title, v.category, v.description, v.pair_price_kes::integer, v.featured::boolean
FROM (VALUES
  ('head-lens-harrier-2014-2019-47-148', 'nx-harrier-head-lens', 'Head lens – Harrier 2014–2019', 'Head lenses', 'High-clarity optical grade polycarbonate replacement head lens for 2014-2019 Toyota Harrier. UV coated against yellowing and oxidation. Restores factory beam throw.', 7800, true),
  ('head-lens-premio-240-20-412', 'nx-premio-240-head-lens', 'Head lens – Premio 240', 'Head lenses', 'Direct replacement headlight lens for Toyota Premio 240. Crystal clear finish, exact tab matching for seamless Kirinyaga Road counter fitting.', 3300, true),
  ('head-lens-premio-260-20-448', 'nx-premio-260-head-lens', 'Head lens – Premio 260', 'Head lenses', 'OEM fit clear headlamp lens for Toyota Premio 260. Replaces pitted, frosted or yellowed original lenses without buying entire housing.', 3800, true),
  ('head-lens-probox-old-52-089', 'nx-probox-old-head-lens', 'Head lens – Probox Old', 'Head lenses', 'Durable clear replacement lens for old model Probox and Succeed. Built tough for matatu and commercial fleet use.', 2800, false),
  ('head-lens-probox-new-shape-52-192', 'nx-probox-new-head-lens', 'Head lens – Probox New Shape', 'Head lenses', 'Replacement headlens for modern facelift Toyota Probox NSP160 series. Flawless optical clarity.', 2900, false),
  ('head-lens-vitz-jewela-52-210', 'nx-vitz-jewela-head-lens', 'Head lens – Vitz Jewela', 'Head lenses', 'Precision molded lens with chrome inner reflector channel profile. Specially fitted for Vitz Jewela trim.', 3800, false),
  ('head-lens-axio-fielder-06-12-12-490', 'nx-axio-08-head-lens', 'Head lens – Axio / Fielder 06–12', 'Head lenses', 'High impact acrylic polycarbonate front lens for Corolla Axio and Fielder 140 models.', 3400, false),
  ('tail-lens-premio-260-20-466', 'nx-premio-260-tail-lens', 'Tail lens – Premio 260', 'Tail lenses', 'Rear tail light lens for Toyota Premio 260. Signature ruby red and diamond clear sections, heat sealed against moisture.', 2800, true),
  ('tail-lens-probox-old-52-031', 'nx-probox-old-tail-lens', 'Tail lens – Probox Old', 'Tail lenses', 'Economical, rugged replacement rear tail lamp lens. The Kirinyaga Road daily best-seller.', 1200, true),
  ('tail-lens-probox-new-160-52-160', 'nx-probox-new-tail-lens', 'Tail lens – Probox New (160)', 'Tail lenses', 'Updated clear and red rear combination tail lens for post-2014 Probox models.', 2300, false),
  ('tail-lens-vitz-jewela-52-212', 'nx-vitz-jewela-tail-lens', 'Tail lens – Vitz Jewela', 'Tail lenses', 'Outer corner tail lens replacement with clear reverse and indicator pods.', 1750, false),
  ('tail-lens-fielder-13-19-12-580', 'nx-fielder-13-19-tail-lens', 'Tail lens – Fielder 13–19', 'Tail lenses', 'Sleek aerodynamic tail lens for Corolla Fielder wagon models.', 2300, false),
  ('tail-lens-prado-j150-60-150', 'nx-prado-150-tail-lens', 'Tail lens – Prado J150', 'Tail lenses', 'Original grade tail lens replacement for Prado 150. Heavy duty thermal sealed housing.', 4800, true),
  ('tail-lamp-suzuki-alto-ha36-71-036', 'nx-alto-tail-lamp', 'Tail lamp – Suzuki Alto HA36', 'Tail lenses', 'Complete tail lamp lens unit with bulb holder. Instant plug & play fitting.', 4800, false),
  ('fog-lamp-premio-nyoka-260-fl-260', 'nx-premio-nyoka-fog-lamp', 'Fog lamp – Premio Nyoka (260)', 'Fog lamps', 'Bumper mounted fog lamp unit with glass lens and internal reflector for dense morning Rift Valley / Limuru fog.', 1900, true),
  ('fog-cover-fielder-2015-fc-161', 'nx-fielder-15-fog-cover', 'Fog cover – Fielder 2015', 'Fog lamps', 'Textured black OEM snap-in fog lamp grille cover.', 1500, false),
  ('fog-lamp-probox-succeed-fl-501', 'nx-succeed-fog-lamp', 'Fog lamp – Probox / Succeed', 'Fog lamps', 'Direct bolt-on fog lamp unit with halogen bulb socket.', 1700, false),
  ('m8-pro-led-bulb-h4-premio-probox-nze-m8-h4-60k', 'nx-led-m8-pro-h4', 'M8 PRO LED Bulb – H4 (Premio / Probox / NZE)', 'LED lighting', 'Super bright 6000K crisp white LED conversion kit. Built-in silent cooling fan, sharp cutoff line, no glare for oncoming drivers on Kenyan highways.', 2800, true),
  ('m8-pro-led-bulb-h11-m8-h11-60k', 'nx-led-m8-pro-h11', 'M8 PRO LED Bulb – H11', 'LED lighting', 'Pure white 6000K aviation aluminum LED bulb. Instant 0.1s startup time, perfect for night driving along Thika Superhighway.', 2600, false),
  ('y8-mini-projector-led-h4-y8-mini-h4', 'nx-led-y8-h4-projector', 'Y8 Mini Projector LED – H4', 'LED lighting', 'Self-contained mini projector lens built into the bulb. Projects laser-sharp flat beam cutoff directly onto road surface without scattering.', 4800, true),
  ('cob-yellow-fog-ribbon-12v-cob-yel-5m', 'nx-cob-yellow-fog-strip', 'COB Yellow Fog Ribbon 12V', 'LED lighting', 'High density dotless flexible COB LED strip. Intense golden yellow light punches through rain and heavy fog.', NULL, false),
  ('tpe-floor-mats-harrier-2014-2024-tpe-ha-xu60', 'nx-tpe-harrier-mats', 'TPE Floor Mats – Harrier 2014–2024', 'Mats & TPE', 'Heavy duty, odorless thermoplastic elastomer (TPE) molded floor liner set. Deep containment ridges trap red Nairobi mud, spilled water, and gravel.', NULL, true),
  ('tpe-floor-mats-prado-150-7-seater-tpe-prado-7s', 'nx-tpe-prado-tx-7seater', 'TPE Floor Mats – Prado 150 (7 Seater)', 'Mats & TPE', 'Full 3-row laser scanned deep dish TPE all-weather mat set. Waterproof, easily hosed clean, anti-skid retention tabs.', NULL, true),
  ('tpe-floor-mats-corolla-nze-tpe-nze-121', 'nx-tpe-nze-mats', 'TPE Floor Mats – Corolla NZE', 'Mats & TPE', 'Tailored molded floor mats that hug the exact footwell contours of the Corolla NZE.', NULL, false),
  ('trd-floor-mats-toyota-5-piece-trd-mat-5pc', 'nx-trd-floor-mat-set', 'TRD Floor Mats – Toyota (5-Piece)', 'Mats & TPE', 'Durable rubber backing with embossed red and black TRD Sport badge. Anti-slip backing keeps mats in position under pedal area.', NULL, true),
  ('windbreaker-visors-premio-260-wb-pr-260', 'nx-wb-premio-260', 'Windbreaker visors – Premio 260', 'Windbreakers', '4-piece aerodynamic dark smoke acrylic door visors. Pre-applied automotive 3M adhesive tape. Deflects rain while allowing fresh air ventilation.', NULL, true),
  ('windbreaker-visors-harrier-14-18-wb-ha-1418', 'nx-wb-harrier-14-18', 'Windbreaker visors – Harrier 14–18', 'Windbreakers', 'Sleek flush contour door window visors tailored specifically for Harrier 2014–2019 frame.', NULL, false),
  ('windbreaker-visors-probox-succeed-wb-pb-all', 'nx-wb-probox-succeed', 'Windbreaker visors – Probox / Succeed', 'Windbreakers', 'Tough wide-profile rain guard visors. Heavy duty acrylic built to withstand sun and highway wind pressure.', NULL, true),
  ('windbreaker-visors-fielder-12-17-wb-fd-1217', 'nx-wb-fielder-12-17', 'Windbreaker visors – Fielder 12–17', 'Windbreakers', 'Precision molded tinted window deflectors with high gloss smoked finish.', NULL, false),
  ('windbreaker-visors-mazda-cx-5-wb-cx5-kf', 'nx-wb-cx5-16-22', 'Windbreaker visors – Mazda CX-5', 'Windbreakers', 'Sporty chrome-edge accent or piano black acrylic rain visors tailored for Mazda CX-5.', NULL, false),
  ('3-step-chrome-grille-hiace-200-cr-hce-3stp', 'nx-chrome-hiace-3step-grill', '3-Step Chrome Grille – Hiace 200', 'Chrome kits', 'Triple-plated mirror chrome front luxury replacement grille for Toyota Hiace. Transforms the front look of commercial and passenger vans.', NULL, true),
  ('chrome-kit-probox-2012-trd-cr-pb-trd12', 'nx-chrome-probox-trd-trim', 'Chrome Kit – Probox 2012 TRD', 'Chrome kits', 'Complete exterior styling kit including chrome door handle covers, rear plate garnish, and mirror caps.', NULL, false),
  ('hydraulic-bottle-jack-5-ton-jk-bot-5t', 'nx-hydraulic-jack-5t', 'Hydraulic Bottle Jack (5 Ton)', 'Accessories & Tools', 'Solid steel forged hydraulic cylinder with overload bypass safety valve and 2-piece pumping lever. Compact roadside companion.', NULL, true),
  ('metallic-life-saver-triangle-pair-ls-met-pair', 'nx-metallic-life-saver', 'Metallic Life Saver Triangle (Pair)', 'Accessories & Tools', 'Wind-resistant heavy cast iron weighted base. High intensity prismatic red reflector, visible from 200m at night.', NULL, false),
  ('battery-jumper-cables-500-amp-jc-500a-3m', 'nx-jumper-cables-heavy', 'Battery Jumper Cables (500 Amp)', 'Accessories & Tools', '100% pure copper clad wiring with insulated alligator clamps. Starts completely drained batteries safely.', NULL, false),
  ('stone-guard-fender-liner-nze-sg-nze-121', 'nx-stone-guard-nze', 'Stone Guard / Fender Liner – NZE', 'Accessories & Tools', 'Prevents road pebbles, mud and water from hitting engine bay and wiring harness.', 1900, false)
) AS v (slug, legacy_id, title, category, description, pair_price_kes, featured)
ON CONFLICT (slug) DO UPDATE SET
  legacy_id = EXCLUDED.legacy_id, title = EXCLUDED.title, category = EXCLUDED.category,
  description = EXCLUDED.description, pair_price_kes = EXCLUDED.pair_price_kes,
  featured = EXCLUDED.featured;

INSERT INTO parts (product_id, sku, erpnext_item_code, side, unit, price_kes, stock_qty)
SELECT pr.id, v.sku, v.erpnext_item_code, v.side, v.unit, v.price_kes::integer, v.stock_qty::integer
FROM (VALUES
  ('head-lens-harrier-2014-2019-47-148', 'HEAD LENS HARRIER 2014-2019 LH', 'HEAD LENS HARRIER 2014-2019', 'LH', 'Pc', 4025, 14),
  ('head-lens-harrier-2014-2019-47-148', 'HEAD LENS HARRIER 2014-2019 RH', 'HEAD LENS HARRIER 2014-2019', 'RH', 'Pc', 4025, 14),
  ('head-lens-premio-240-20-412', 'HEAD LENS PREMIO 240 LH', 'HEAD LENS PREMIO 240', 'LH', 'Pc', 1700, 5),
  ('head-lens-premio-240-20-412', 'HEAD LENS PREMIO 240 RH', 'HEAD LENS PREMIO 240', 'RH', 'Pc', 1700, 5),
  ('head-lens-premio-260-20-448', 'Head Lense Premio 260 LH', 'Head Lense Premio 260', 'LH', 'Pc', 2000, 6),
  ('head-lens-premio-260-20-448', 'Head Lense Premio 260 RH', 'Head Lense Premio 260', 'RH', 'Pc', 2000, 6),
  ('head-lens-probox-old-52-089', 'Head Lense Probox OLD LH', 'Head Lense Probox OLD', 'LH', 'Pc', 1500, 8),
  ('head-lens-probox-old-52-089', 'Head Lense Probox OLD RH', 'Head Lense Probox OLD', 'RH', 'Pc', 1500, 8),
  ('head-lens-probox-new-shape-52-192', 'HEAD LENS PROBOX NEW LH', 'HEAD LENS PROBOX NEW', 'LH', 'Pc', 1500, 4),
  ('head-lens-probox-new-shape-52-192', 'HEAD LENS PROBOX NEW RH', 'HEAD LENS PROBOX NEW', 'RH', 'Pc', 1500, 4),
  ('head-lens-vitz-jewela-52-210', 'HEAD LENSE VITZ JEWELA 2012 LH', 'HEAD LENSE VITZ JEWELA 2012', 'LH', 'Pc', 2000, 4),
  ('head-lens-vitz-jewela-52-210', 'HEAD LENSE VITZ JEWELA 2012 RH', 'HEAD LENSE VITZ JEWELA 2012', 'RH', 'Pc', 2000, 4),
  ('head-lens-axio-fielder-06-12-12-490', 'HEAD LENS-AXIO 08 LH', 'HEAD LENS-AXIO 08', 'LH', 'Pc', 1800, 5),
  ('head-lens-axio-fielder-06-12-12-490', 'HEAD LENS-AXIO 08 RH', 'HEAD LENS-AXIO 08', 'RH', 'Pc', 1800, 5),
  ('tail-lens-premio-260-20-466', 'Tail Lens Premio 260 LH', 'Tail Lens Premio 260', 'LH', 'Pc', 1500, 7),
  ('tail-lens-premio-260-20-466', 'Tail Lens Premio 260 RH', 'Tail Lens Premio 260', 'RH', 'Pc', 1500, 7),
  ('tail-lens-probox-old-52-031', 'TAIL LENS PROBOX Old LH', 'TAIL LENS PROBOX Old', 'LH', 'Pc', 650, 12),
  ('tail-lens-probox-old-52-031', 'TAIL LENS PROBOX Old RH', 'TAIL LENS PROBOX Old', 'RH', 'Pc', 650, 12),
  ('tail-lens-probox-new-160-52-160', 'TAIL LENS PROBOX New LH', 'TAIL LENS PROBOX New', 'LH', 'Pc', 1200, 6),
  ('tail-lens-probox-new-160-52-160', 'TAIL LENS PROBOX New RH', 'TAIL LENS PROBOX New', 'RH', 'Pc', 1200, 6),
  ('tail-lens-vitz-jewela-52-212', 'Tail Lens Vitz Jewela LH', 'Tail Lens Vitz Jewela', 'LH', 'Pc', 900, 8),
  ('tail-lens-vitz-jewela-52-212', 'Tail Lens Vitz Jewela RH', 'Tail Lens Vitz Jewela', 'RH', 'Pc', 900, 8),
  ('tail-lens-fielder-13-19-12-580', 'TAIL LENS FIEDER 2013-2019 LH', 'TAIL LENS FIEDER 2013-2019', 'LH', 'Pc', 1200, 6),
  ('tail-lens-fielder-13-19-12-580', 'TAIL LENS FIEDER 2013-2019 RH', 'TAIL LENS FIEDER 2013-2019', 'RH', 'Pc', 1200, 6),
  ('tail-lens-prado-j150-60-150', 'TAIL LENS PRADO 150 LH', 'TAIL LENS PRADO 150', 'LH', 'Pc', 2500, 4),
  ('tail-lens-prado-j150-60-150', 'TAIL LENS PRADO 150 RH', 'TAIL LENS PRADO 150', 'RH', 'Pc', 2500, 4),
  ('tail-lamp-suzuki-alto-ha36-71-036', 'TAIL LAMP ALTO SUZUKI 2015-2019 LH', 'TAIL LAMP ALTO SUZUKI 2015-2019', 'LH', 'Pc', 2500, 4),
  ('tail-lamp-suzuki-alto-ha36-71-036', 'TAIL LAMP ALTO SUZUKI 2015-2019 RH', 'TAIL LAMP ALTO SUZUKI 2015-2019', 'RH', 'Pc', 2500, 4),
  ('fog-lamp-premio-nyoka-260-fl-260', 'FOG LAMP PREMIO NYOKA LH', 'FOG LAMP PREMIO NYOKA', 'LH', 'Pc', 1000, 6),
  ('fog-lamp-premio-nyoka-260-fl-260', 'FOG LAMP PREMIO NYOKA RH', 'FOG LAMP PREMIO NYOKA', 'RH', 'Pc', 1000, 6),
  ('fog-cover-fielder-2015-fc-161', 'FOG COVER FIELDER 2015 LH', 'FOG COVER FIELDER 2015', 'LH', 'Pc', 800, 4),
  ('fog-cover-fielder-2015-fc-161', 'FOG COVER FIELDER 2015 RH', 'FOG COVER FIELDER 2015', 'RH', 'Pc', 800, 4),
  ('fog-lamp-probox-succeed-fl-501', 'FOG LAMP SUCEED LH', 'FOG LAMP SUCEED', 'LH', 'Pc', 900, 6),
  ('fog-lamp-probox-succeed-fl-501', 'FOG LAMP SUCEED RH', 'FOG LAMP SUCEED', 'RH', 'Pc', 900, 6),
  ('m8-pro-led-bulb-h4-premio-probox-nze-m8-h4-60k', 'M8 PRO-H4', 'M8 PRO-H4', 'pair', 'Pc', 1500, 10),
  ('m8-pro-led-bulb-h11-m8-h11-60k', 'M8 PRO-H 11', 'M8 PRO-H 11', 'pair', 'Pc', 1400, 8),
  ('y8-mini-projector-led-h4-y8-mini-h4', 'Y8-H4', 'Y8-H4', 'pair', 'Pc', 2500, 12),
  ('cob-yellow-fog-ribbon-12v-cob-yel-5m', 'COB-YELLOW-12V', 'COB-YELLOW-12V', 'universal', 'Roll', 650, 15),
  ('tpe-floor-mats-harrier-2014-2024-tpe-ha-xu60', 'TPE-HA 14-24', 'TPE-HA 14-24', 'pair', 'Set', 4900, 10),
  ('tpe-floor-mats-prado-150-7-seater-tpe-prado-7s', 'TPE-PRA TX-7 SEATER', 'TPE-PRA TX-7 SEATER', 'pair', 'Set', 6500, 8),
  ('tpe-floor-mats-corolla-nze-tpe-nze-121', 'TPE-NZE 10-24', 'TPE-NZE 10-24', 'pair', 'Set', 4500, 10),
  ('trd-floor-mats-toyota-5-piece-trd-mat-5pc', 'TOYOTA-TRD-FLOOR-MAT', 'TOYOTA-TRD-FLOOR-MAT', 'pair', 'Set', 1800, 15),
  ('windbreaker-visors-premio-260-wb-pr-260', 'WINDBREAKER-PREMIO-260', 'WINDBREAKER-PREMIO-260', 'pair', 'Set', 1500, 12),
  ('windbreaker-visors-harrier-14-18-wb-ha-1418', 'WINDBREAKER HARRIER 2014-2018', 'WINDBREAKER HARRIER 2014-2018', 'pair', 'Set', 1600, 8),
  ('windbreaker-visors-probox-succeed-wb-pb-all', 'WINDBREAKER-PROBOX/SUCCEED', 'WINDBREAKER-PROBOX/SUCCEED', 'pair', 'Set', 1400, 15),
  ('windbreaker-visors-fielder-12-17-wb-fd-1217', 'WINDBREAKER FIELDER 2012-2017', 'WINDBREAKER FIELDER 2012-2017', 'pair', 'Set', 1500, 7),
  ('windbreaker-visors-mazda-cx-5-wb-cx5-kf', 'WIND BREAKER MAZDA CX5 2016-2022', 'WIND BREAKER MAZDA CX5 2016-2022', 'pair', 'Set', 1800, 6),
  ('3-step-chrome-grille-hiace-200-cr-hce-3stp', 'GRILL-HAICE-3--STEP', 'GRILL-HAICE-3--STEP', 'universal', 'Pc', 7500, 4),
  ('chrome-kit-probox-2012-trd-cr-pb-trd12', 'CHROM KIT PROBOX 2012 TRD TAN COVER', 'CHROM KIT PROBOX 2012 TRD TAN COVER', 'pair', 'Set', 5800, 5),
  ('hydraulic-bottle-jack-5-ton-jk-bot-5t', 'HYDRAULIC JACK-5T', 'HYDRAULIC JACK-5T', 'universal', 'Pc', 1850, 12),
  ('metallic-life-saver-triangle-pair-ls-met-pair', 'METALLIC LIFE SAVER', 'METALLIC LIFE SAVER', 'pair', 'Set', 650, 20),
  ('battery-jumper-cables-500-amp-jc-500a-3m', 'JAMPER CABLE', 'JAMPER CABLE', 'universal', 'Set', 850, 14),
  ('stone-guard-fender-liner-nze-sg-nze-121', 'STONE GUARD NZE LH', 'STONE GUARD NZE', 'LH', 'Pc', 1000, 6),
  ('stone-guard-fender-liner-nze-sg-nze-121', 'STONE GUARD NZE RH', 'STONE GUARD NZE', 'RH', 'Pc', 1000, 6)
) AS v (product_slug, sku, erpnext_item_code, side, unit, price_kes, stock_qty)
JOIN products pr ON pr.slug = v.product_slug
ON CONFLICT (sku) DO UPDATE SET
  erpnext_item_code = EXCLUDED.erpnext_item_code, side = EXCLUDED.side, unit = EXCLUDED.unit,
  price_kes = EXCLUDED.price_kes, stock_qty = EXCLUDED.stock_qty;

-- partNo in src/data is the catalogue number printed on the part/box, not a Toyota OEM number.
INSERT INTO part_numbers (product_id, number, kind)
SELECT pr.id, v.number, 'manufacturer'
FROM (VALUES
  ('head-lens-harrier-2014-2019-47-148', '47-148'),
  ('head-lens-premio-240-20-412', '20-412'),
  ('head-lens-premio-260-20-448', '20-448'),
  ('head-lens-probox-old-52-089', '52-089'),
  ('head-lens-probox-new-shape-52-192', '52-192'),
  ('head-lens-vitz-jewela-52-210', '52-210'),
  ('head-lens-axio-fielder-06-12-12-490', '12-490'),
  ('tail-lens-premio-260-20-466', '20-466'),
  ('tail-lens-probox-old-52-031', '52-031'),
  ('tail-lens-probox-new-160-52-160', '52-160'),
  ('tail-lens-vitz-jewela-52-212', '52-212'),
  ('tail-lens-fielder-13-19-12-580', '12-580'),
  ('tail-lens-prado-j150-60-150', '60-150'),
  ('tail-lamp-suzuki-alto-ha36-71-036', '71-036'),
  ('fog-lamp-premio-nyoka-260-fl-260', 'FL-260'),
  ('fog-cover-fielder-2015-fc-161', 'FC-161'),
  ('fog-lamp-probox-succeed-fl-501', 'FL-501'),
  ('m8-pro-led-bulb-h4-premio-probox-nze-m8-h4-60k', 'M8-H4-60K'),
  ('m8-pro-led-bulb-h11-m8-h11-60k', 'M8-H11-60K'),
  ('y8-mini-projector-led-h4-y8-mini-h4', 'Y8-MINI-H4'),
  ('cob-yellow-fog-ribbon-12v-cob-yel-5m', 'COB-YEL-5M'),
  ('tpe-floor-mats-harrier-2014-2024-tpe-ha-xu60', 'TPE-HA-XU60'),
  ('tpe-floor-mats-prado-150-7-seater-tpe-prado-7s', 'TPE-PRADO-7S'),
  ('tpe-floor-mats-corolla-nze-tpe-nze-121', 'TPE-NZE-121'),
  ('trd-floor-mats-toyota-5-piece-trd-mat-5pc', 'TRD-MAT-5PC'),
  ('windbreaker-visors-premio-260-wb-pr-260', 'WB-PR-260'),
  ('windbreaker-visors-harrier-14-18-wb-ha-1418', 'WB-HA-1418'),
  ('windbreaker-visors-probox-succeed-wb-pb-all', 'WB-PB-ALL'),
  ('windbreaker-visors-fielder-12-17-wb-fd-1217', 'WB-FD-1217'),
  ('windbreaker-visors-mazda-cx-5-wb-cx5-kf', 'WB-CX5-KF'),
  ('3-step-chrome-grille-hiace-200-cr-hce-3stp', 'CR-HCE-3STP'),
  ('chrome-kit-probox-2012-trd-cr-pb-trd12', 'CR-PB-TRD12'),
  ('hydraulic-bottle-jack-5-ton-jk-bot-5t', 'JK-BOT-5T'),
  ('metallic-life-saver-triangle-pair-ls-met-pair', 'LS-MET-PAIR'),
  ('battery-jumper-cables-500-amp-jc-500a-3m', 'JC-500A-3M'),
  ('stone-guard-fender-liner-nze-sg-nze-121', 'SG-NZE-121')
) AS v (product_slug, number)
JOIN products pr ON pr.slug = v.product_slug
ON CONFLICT (product_id, number, kind) DO NOTHING;

INSERT INTO product_fitments (product_id, generation_id)
SELECT pr.id, g.id
FROM (VALUES
  ('head-lens-harrier-2014-2019-47-148', 'toyota-harrier-xu60'),
  ('head-lens-premio-240-20-412', 'toyota-premio-240'),
  ('head-lens-premio-260-20-448', 'toyota-premio-260'),
  ('head-lens-probox-old-52-089', 'toyota-probox-old'),
  ('head-lens-probox-new-shape-52-192', 'toyota-probox-new'),
  ('head-lens-vitz-jewela-52-210', 'toyota-vitz-jewela'),
  ('head-lens-axio-fielder-06-12-12-490', 'toyota-axio-e140'),
  ('head-lens-axio-fielder-06-12-12-490', 'toyota-fielder-140'),
  ('tail-lens-premio-260-20-466', 'toyota-premio-260'),
  ('tail-lens-premio-260-20-466', 'toyota-allion-260'),
  ('tail-lens-probox-old-52-031', 'toyota-probox-old'),
  ('tail-lens-probox-new-160-52-160', 'toyota-probox-new'),
  ('tail-lens-vitz-jewela-52-212', 'toyota-vitz-jewela'),
  ('tail-lens-fielder-13-19-12-580', 'toyota-fielder-160'),
  ('tail-lens-prado-j150-60-150', 'toyota-prado-150'),
  ('tail-lamp-suzuki-alto-ha36-71-036', 'suzuki-alto'),
  ('fog-lamp-premio-nyoka-260-fl-260', 'toyota-premio-260'),
  ('fog-cover-fielder-2015-fc-161', 'toyota-fielder-160'),
  ('fog-cover-fielder-2015-fc-161', 'toyota-axio-e160'),
  ('fog-lamp-probox-succeed-fl-501', 'toyota-probox-old'),
  ('fog-lamp-probox-succeed-fl-501', 'toyota-probox-new'),
  ('m8-pro-led-bulb-h4-premio-probox-nze-m8-h4-60k', 'toyota-premio-260'),
  ('m8-pro-led-bulb-h4-premio-probox-nze-m8-h4-60k', 'toyota-premio-240'),
  ('m8-pro-led-bulb-h4-premio-probox-nze-m8-h4-60k', 'toyota-probox-old'),
  ('m8-pro-led-bulb-h4-premio-probox-nze-m8-h4-60k', 'toyota-probox-new'),
  ('m8-pro-led-bulb-h4-premio-probox-nze-m8-h4-60k', 'toyota-corolla-nze'),
  ('m8-pro-led-bulb-h4-premio-probox-nze-m8-h4-60k', 'suzuki-alto'),
  ('m8-pro-led-bulb-h11-m8-h11-60k', 'toyota-harrier-xu60'),
  ('m8-pro-led-bulb-h11-m8-h11-60k', 'toyota-axio-e160'),
  ('m8-pro-led-bulb-h11-m8-h11-60k', 'toyota-fielder-160'),
  ('m8-pro-led-bulb-h11-m8-h11-60k', 'mazda-cx5'),
  ('y8-mini-projector-led-h4-y8-mini-h4', 'toyota-premio-240'),
  ('y8-mini-projector-led-h4-y8-mini-h4', 'toyota-probox-old'),
  ('y8-mini-projector-led-h4-y8-mini-h4', 'toyota-corolla-nze'),
  ('cob-yellow-fog-ribbon-12v-cob-yel-5m', 'toyota-premio-260'),
  ('cob-yellow-fog-ribbon-12v-cob-yel-5m', 'toyota-probox-old'),
  ('cob-yellow-fog-ribbon-12v-cob-yel-5m', 'toyota-hiace-200'),
  ('tpe-floor-mats-harrier-2014-2024-tpe-ha-xu60', 'toyota-harrier-xu60'),
  ('tpe-floor-mats-prado-150-7-seater-tpe-prado-7s', 'toyota-prado-150'),
  ('tpe-floor-mats-corolla-nze-tpe-nze-121', 'toyota-corolla-nze'),
  ('trd-floor-mats-toyota-5-piece-trd-mat-5pc', 'toyota-premio-260'),
  ('trd-floor-mats-toyota-5-piece-trd-mat-5pc', 'toyota-premio-240'),
  ('trd-floor-mats-toyota-5-piece-trd-mat-5pc', 'toyota-axio-e140'),
  ('trd-floor-mats-toyota-5-piece-trd-mat-5pc', 'toyota-fielder-140'),
  ('trd-floor-mats-toyota-5-piece-trd-mat-5pc', 'toyota-probox-old'),
  ('trd-floor-mats-toyota-5-piece-trd-mat-5pc', 'toyota-vitz-jewela'),
  ('windbreaker-visors-premio-260-wb-pr-260', 'toyota-premio-260'),
  ('windbreaker-visors-premio-260-wb-pr-260', 'toyota-allion-260'),
  ('windbreaker-visors-harrier-14-18-wb-ha-1418', 'toyota-harrier-xu60'),
  ('windbreaker-visors-probox-succeed-wb-pb-all', 'toyota-probox-old'),
  ('windbreaker-visors-probox-succeed-wb-pb-all', 'toyota-probox-new'),
  ('windbreaker-visors-fielder-12-17-wb-fd-1217', 'toyota-fielder-160'),
  ('windbreaker-visors-mazda-cx-5-wb-cx5-kf', 'mazda-cx5'),
  ('3-step-chrome-grille-hiace-200-cr-hce-3stp', 'toyota-hiace-200'),
  ('chrome-kit-probox-2012-trd-cr-pb-trd12', 'toyota-probox-old'),
  ('hydraulic-bottle-jack-5-ton-jk-bot-5t', 'toyota-premio-260'),
  ('hydraulic-bottle-jack-5-ton-jk-bot-5t', 'toyota-harrier-xu60'),
  ('hydraulic-bottle-jack-5-ton-jk-bot-5t', 'toyota-probox-old'),
  ('hydraulic-bottle-jack-5-ton-jk-bot-5t', 'toyota-prado-150'),
  ('metallic-life-saver-triangle-pair-ls-met-pair', 'toyota-premio-260'),
  ('metallic-life-saver-triangle-pair-ls-met-pair', 'toyota-harrier-xu60'),
  ('metallic-life-saver-triangle-pair-ls-met-pair', 'toyota-probox-old'),
  ('battery-jumper-cables-500-amp-jc-500a-3m', 'toyota-premio-260'),
  ('battery-jumper-cables-500-amp-jc-500a-3m', 'toyota-harrier-xu60'),
  ('battery-jumper-cables-500-amp-jc-500a-3m', 'toyota-probox-old'),
  ('stone-guard-fender-liner-nze-sg-nze-121', 'toyota-corolla-nze')
) AS v (product_slug, generation_slug)
JOIN products pr ON pr.slug = v.product_slug
JOIN vehicle_generations g ON g.slug = v.generation_slug
ON CONFLICT (product_id, generation_id, position,
             coalesce(year_from, 0), coalesce(year_to, 0), coalesce(engine_id, 0)) DO NOTHING;

COMMIT;
