// Generates db/seeds/001_catalog.sql from src/data/*.ts.
// Run with: npm run db:seed:generate
import { writeFileSync } from 'node:fs';
import { VEHICLE_DATABASE } from '../../src/data/vehicles';
import { PRODUCTS } from '../../src/data/products';
import type { ProductItem } from '../../src/types';

// vehicles.ts stores generation names ("Premio 260"); the base model has to be named explicitly.
const BASE_MODEL: Record<string, string> = {
  'toyota-premio-260': 'Premio',
  'toyota-premio-240': 'Premio',
  'toyota-harrier-xu60': 'Harrier',
  'toyota-harrier-xu30': 'Harrier',
  'toyota-probox-old': 'Probox / Succeed',
  'toyota-probox-new': 'Probox / Succeed',
  'toyota-corolla-nze': 'Corolla',
  'toyota-axio-e140': 'Corolla Axio',
  'toyota-axio-e160': 'Corolla Axio',
  'toyota-fielder-140': 'Corolla Fielder',
  'toyota-fielder-160': 'Corolla Fielder',
  'toyota-prado-150': 'Land Cruiser Prado',
  'toyota-vitz-jewela': 'Vitz',
  'toyota-vitz-05': 'Vitz',
  'toyota-voxy-noah-70': 'Noah / Voxy',
  'toyota-hiace-200': 'Hiace',
  'toyota-allion-260': 'Allion',
  'toyota-allion-240': 'Allion',
  'mazda-demio': 'Demio',
  'mazda-cx5': 'CX-5',
  'subaru-forester-sj': 'Forester',
  'suzuki-alto': 'Alto',
  'nissan-tiida-c11': 'Tiida',
  'nissan-nv200': 'NV200 Vanette',
};

const SIDES: Record<ProductItem['sideAvailable'], string[]> = {
  BOTH_SIDES: ['LH', 'RH'],
  LH_ONLY: ['LH'],
  RH_ONLY: ['RH'],
  PAIR_ONLY: ['pair'],
  UNIVERSAL: ['universal'],
};

const slugify = (s: string) =>
  s
    .toLowerCase()
    .replace(/[–—]/g, '-')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

const q = (v: string | number | boolean | null | undefined) =>
  v === null || v === undefined
    ? 'NULL'
    : typeof v === 'string'
      ? `'${v.replace(/'/g, "''")}'`
      : String(v);

const values = (rows: unknown[][]) =>
  rows.map((r) => `  (${r.map((v) => q(v as string)).join(', ')})`).join(',\n');

const vehicleIds = new Set(VEHICLE_DATABASE.map((v) => v.id));
for (const v of VEHICLE_DATABASE) {
  if (!BASE_MODEL[v.id]) throw new Error(`Add a BASE_MODEL entry for vehicle "${v.id}"`);
}

const makes = [...new Set(VEHICLE_DATABASE.map((v) => v.make))];
const models = [
  ...new Map(
    VEHICLE_DATABASE.map((v) => {
      const name = BASE_MODEL[v.id];
      return [`${v.make}|${name}`, [slugify(v.make), name, slugify(name)]];
    }),
  ).values(),
];

const productSlugs = new Set<string>();
const products = PRODUCTS.map((p) => {
  const slug = slugify(`${p.cleanTitle} ${p.partNo}`);
  if (productSlugs.has(slug)) throw new Error(`Duplicate product slug "${slug}"`);
  productSlugs.add(slug);
  for (const vid of p.fitVehicles) {
    if (!vehicleIds.has(vid)) throw new Error(`Product "${p.id}" fits unknown vehicle "${vid}"`);
  }
  return { p, slug };
});

const sql = `-- GENERATED by db/seeds/generate-catalog-seed.ts from src/data/*.ts. Do not edit by hand.
-- Re-runnable: every insert upserts on its natural key.
-- TODO: per-side stock comes from ERPNext; until then both sides get the product's inStock count.

BEGIN;

INSERT INTO makes (name, slug) VALUES
${values(makes.map((m) => [m, slugify(m)]))}
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO models (make_id, name, slug)
SELECT mk.id, v.name, v.slug
FROM (VALUES
${values(models)}
) AS v (make_slug, name, slug)
JOIN makes mk ON mk.slug = v.make_slug
ON CONFLICT (make_id, slug) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO vehicle_generations (model_id, name, slug, year_from, year_to, popular)
SELECT mo.id, v.name, v.slug, v.year_from::smallint, v.year_to::smallint, v.popular::boolean
FROM (VALUES
${values(
  VEHICLE_DATABASE.map((v) => [
    slugify(v.make),
    slugify(BASE_MODEL[v.id]),
    v.model,
    v.id,
    v.yearMin,
    v.yearMax,
    !!v.popular,
  ]),
)}
) AS v (make_slug, model_slug, name, slug, year_from, year_to, popular)
JOIN makes mk ON mk.slug = v.make_slug
JOIN models mo ON mo.make_id = mk.id AND mo.slug = v.model_slug
ON CONFLICT (slug) DO UPDATE SET
  model_id = EXCLUDED.model_id, name = EXCLUDED.name, year_from = EXCLUDED.year_from,
  year_to = EXCLUDED.year_to, popular = EXCLUDED.popular;

INSERT INTO chassis_codes (generation_id, code)
SELECT g.id, v.code
FROM (VALUES
${values(
  VEHICLE_DATABASE.flatMap((v) =>
    v.chassis.split('/').map((c) => [v.id, c.trim()]),
  ),
)}
) AS v (generation_slug, code)
JOIN vehicle_generations g ON g.slug = v.generation_slug
ON CONFLICT (generation_id, code) DO NOTHING;

INSERT INTO products (slug, legacy_id, title, category, description, pair_price_kes, featured)
SELECT v.slug, v.legacy_id, v.title, v.category, v.description, v.pair_price_kes::integer, v.featured::boolean
FROM (VALUES
${values(
  products.map(({ p, slug }) => [
    slug,
    p.id,
    p.cleanTitle,
    p.category,
    p.description,
    p.pairPrice ?? null,
    !!p.featured,
  ]),
)}
) AS v (slug, legacy_id, title, category, description, pair_price_kes, featured)
ON CONFLICT (slug) DO UPDATE SET
  legacy_id = EXCLUDED.legacy_id, title = EXCLUDED.title, category = EXCLUDED.category,
  description = EXCLUDED.description, pair_price_kes = EXCLUDED.pair_price_kes,
  featured = EXCLUDED.featured;

INSERT INTO parts (product_id, sku, erpnext_item_code, side, unit, price_kes, stock_qty)
SELECT pr.id, v.sku, v.erpnext_item_code, v.side, v.unit, v.price_kes::integer, v.stock_qty::integer
FROM (VALUES
${values(
  products.flatMap(({ p, slug }) => {
    const sides = SIDES[p.sideAvailable];
    return sides.map((side) => [
      slug,
      sides.length > 1 ? `${p.itemCode} ${side}` : p.itemCode,
      p.itemCode,
      side,
      p.unit,
      p.price,
      p.inStock,
    ]);
  }),
)}
) AS v (product_slug, sku, erpnext_item_code, side, unit, price_kes, stock_qty)
JOIN products pr ON pr.slug = v.product_slug
ON CONFLICT (sku) DO UPDATE SET
  erpnext_item_code = EXCLUDED.erpnext_item_code, side = EXCLUDED.side, unit = EXCLUDED.unit,
  price_kes = EXCLUDED.price_kes, stock_qty = EXCLUDED.stock_qty;

-- partNo in src/data is the catalogue number printed on the part/box, not a Toyota OEM number.
INSERT INTO part_numbers (product_id, number, kind)
SELECT pr.id, v.number, 'manufacturer'
FROM (VALUES
${values(products.filter(({ p }) => p.partNo).map(({ p, slug }) => [slug, p.partNo]))}
) AS v (product_slug, number)
JOIN products pr ON pr.slug = v.product_slug
ON CONFLICT (product_id, number, kind) DO NOTHING;

INSERT INTO product_fitments (product_id, generation_id)
SELECT pr.id, g.id
FROM (VALUES
${values(products.flatMap(({ p, slug }) => p.fitVehicles.map((vid) => [slug, vid])))}
) AS v (product_slug, generation_slug)
JOIN products pr ON pr.slug = v.product_slug
JOIN vehicle_generations g ON g.slug = v.generation_slug
ON CONFLICT (product_id, generation_id, position,
             coalesce(year_from, 0), coalesce(year_to, 0), coalesce(engine_id, 0)) DO NOTHING;

COMMIT;
`;

const out = 'db/seeds/001_catalog.sql';
writeFileSync(out, sql);
console.log(`Wrote ${out}: ${VEHICLE_DATABASE.length} vehicles, ${PRODUCTS.length} products`);
